name: Tests
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - label: Linux
            image: ubuntu-latest

    name: ${{ matrix.os.label }}
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - name: Enable Binary Cache
        uses: cachix/cachix-action@v15
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Set up pinned nixpkgs
        run: echo "NIX_PATH=nixpkgs=$(nix-instantiate --eval flake-compat.nix -A defaultNix.inputs.nixpkgs.outPath | sed 's|\"||g')" >> $GITHUB_ENV

      - run: nix-shell --run "cargo test"
